### ISSUE TITLE
masthead

### ISSUE THREAD

**Issue by vivkay** [vivkay/dsn1676-assignment-1#1]
Hi Thomas!

Turns out I did get a bit rusty over the break!

For the stars in the top of the page, should I make them a background image (includng the two stars) or save them as an individual svg that I insert to display-inline on either side of the h1? (or another way entirely?)

Thanks!

@thomasjbradley

**Comment by thomasjbradley** [comment]
Inserting them inline in `<img>` tags would work but isn't ideal.

I would create a single background image with 1 star in it, then using CSS insert the star twice into the background with multiple background images.

**Comment by vivkay** [comment]
Thanks @thomasjbradley.

I was having problems with my stars, but then poked around on github and noticed that this code from another student works well.

```
.star-x {
background-image: url("../img/star.svg"), url("../img/star.svg");
background-position: calc(100% - 10px) center, 10px center;
background-repeat: no-repeat;
background-size: 35px 35px, 35px 35px;
padding: 0 3rem;
}

```

It is now working for me, but I still want to understand why this method (what I originally had) wasn't working. The problem was that only one star would be visible.

Here was my html:

```
    <header class="masthead">
            <div class="title">
                <h1 class="title yotta gutter-2 star-l star-r">Wanted!</h1>
            </div>
    </header>
```

Here was my css:

```

.star-r {
    background-image: url("../img/star.svg");
    background-position: right;
    background-repeat: no-repeat;
    background-size: 20px 20px 20px 20px;
}

.star-l {
    background-image: url("../img/star.svg");
    background-position: right;
    background-repeat: no-repeat;
    background-size: 20px 20px 20px 20px;
}  

.masthead {
    background: transparent url("../img/masthead-bg.png") repeat left center;
    text-align: center;
}

.title {
    background-color: #e7e5d9;
    display: inline-block;
    margin-bottom: 0;
}

```

**Comment by thomasjbradley** [comment]
Check out how I did the multiple background images here:
https://github.com/algonquindesign/html-css/blob/gh-pages/organization-slicing/css/main.css#L83

**Comment by vivkay** [comment]
thanks!
