### ISSUE TITLE
images

### ISSUE THREAD

**Issue by vivkay** [vivkay/dsn1676-assignment-1#2]
Hi @thomasjbradley

For this part of the website (see image) is it better to make the brown box with the icons one image in photoshop (and place it as a background image on the unit), or should I colour the brown box in css, and add the icons as individual and centered .svg's?

![image](https://cloud.githubusercontent.com/assets/6340292/5687459/cdeb6610-981a-11e4-88ad-4cb4b6865380.png)

**Comment by vivkay** [comment]
Sorry not that image, this one.

![screen shot 2015-01-09 at 4 15 22 pm](https://cloud.githubusercontent.com/assets/6340292/5687481/07fa9d44-981b-11e4-8f09-ea87d8cd5104.png)

**Comment by thomasjbradley** [comment]
Brown box should be a background colour, and the images can either be inserted as `<img>` tags, or as background images—background images being the better choice because they're just decoration.

**Comment by vivkay** [comment]
Thanks @thomasjbradley. I am using the method of background images because they're decoration, but for some reason my hat won't display?

Question 1 (disappearing hat):

Here's my html:

```
        <div class="unit unit-xs-1 unit-s-1 unit-m-1-2 unit-l-1-3 brown-box hat cuffs push">
            <h1 class="center peta">Reward $50,000</h1>
            <p class="center mega">For the following crimes</p>
            <ul class="bullets kilo">
                <li>Space piracy</li>
                <li>Illegal asteroid mining</li>
                <li>Galactic Treason</li>
            </ul>
        </div>
```

Here's my css:

```
.hat {
    background-image: url(../img/hat.svg);
    background-repeat: no-repeat;
    text-align: center;
    background-position: top;
    background-size: 50px 50px 50px 50px;
}

.cuffs {
    background-image: url(../img/cuffs.svg);
    background-repeat: no-repeat;
    text-align: center;
    background-position: bottom;
    background-size: 50px 50px;   
}
```

Question 2 (magic sizing):

I also think my handcuffs look silly so small and squished at the bottom here, and with so much excess space!. Since it's not a usual img src element, how can I manipulate this background image to resize at different screen sizes?

Perhaps:
- is there a "height/width: auto" class that might work?
- do I need to manually change the size at different media queries?

Thanks!

![screen shot 2015-01-11 at 10 10 16 am](https://cloud.githubusercontent.com/assets/6340292/5695612/5c06c38a-997a-11e4-85c5-d4e9caab8b48.png)

**Comment by thomasjbradley** [comment]
_Question 1_

It's that the background images are overwriting each other. The hat background image is applied with the  `.hat` class then the CSS cascades down and the `.cuff` class overwrites the background image with a new one. Check out how I've done multiple background images here:
https://github.com/algonquindesign/html-css/blob/gh-pages/organization-slicing/css/main.css#L83

---

_Question 2_

Your `background-size: 50px 50px;` is definitely the right choice. You can try setting that in percents maybe, or use media queries to adjust the sizes.

**Comment by vivkay** [comment]
great! that worked thanks!
