### ISSUE TITLE
border scale

### ISSUE THREAD

**Issue by vivkay** [vivkay/dsn1676-assignment-1#3]
Hi @thomasjbradley, 

I have my borders up here, but they seem to be extremely small compared to our source file. Is this because I sized it down too much in illustrator or is it a css issue?

Thanks!
![screen shot 2015-01-09 at 4 59 09 pm](https://cloud.githubusercontent.com/assets/6340292/5688052/dfa42d64-9820-11e4-95b9-afebdaaad3b7.png)

**Comment by thomasjbradley** [comment]
You're using `border-image`?
What's your `border-width` set at?

**Comment by vivkay** [comment]
This is what I have set for it:

```
.panel {
    border-image: url(../img/border.png) 36 36 36 36 stretch stretch;
    border-width: 36px 36px 36px 36px;
}
```

**Comment by thomasjbradley** [comment]
It's that the PNG itself seems really small:
https://github.com/vivkay/dsn1676-assignment-1/blob/gh-pages/img/border.png

I'm not sure how it got that small, maybe it was scaled down when saving for web?

**Comment by vivkay** [comment]
fixed it in photoshop! Working well now. thanks!
