### ISSUE TITLE
Sizing limit

### ISSUE THREAD

**Issue by vivkay** [vivkay/dsn1676-assignment-1#4]
Hi @thomasjbradley!

I see that we're aiming for 200KB for our website file. I checked mine in finder and my folder totals 429KB...eep! 

I think my main problem are the two jpg images (the photographs). They are 36KB and 39KB each, but I sized them according to your tutorial, and compressed them with image optim also. 

Plus, these jpg's alone don't make my file as small as 200KB.

I have used the SVGO compresser and Image Optim on every image. I'm not sure what else to do?

Thanks!

**Comment by thomasjbradley** [comment]
I downloaded your repository (using the "Download Zip" button on GitHub) onto my computer and you're still undersize.

![screen shot 2015-01-11 at 12 24 58 pm](https://cloud.githubusercontent.com/assets/105192/5696070/0f386c80-998d-11e4-9b71-0566766e13c7.png)

It could be that your GitHub repository history is bloating the file size accidentally.

**Comment by vivkay** [comment]
Ok phew! Thanks for checking that Thomas!!
